### ISSUE TITLE
Fork, deploy and populate the online registry contract from Balancer for assisting with on-chain pool lookups.

### ISSUE THREAD

**Issue by TheNewAutonomy** [centfinance/Symmetric.Core#18]
At least one community project requires access to the registry contract and so this needs to be deployed to Gnosis and Celo and populated with pool data.

https://github.com/balancer-labs/docs/blob/master/smart-contracts/on-chain-registry.md

**Comment by diwu1989** [comment]
On-chain BRegistry deployed and source verified:
https://explorer.celo.org/address/0x3E30b138ecc85cD89210e1A19a8603544A917372/contracts

Doing the backfilling now

**Comment by diwu1989** [comment]
existing pools backfilled into registry, initial sort performed, see registry log:
https://explorer.celo.org/address/0x3E30b138ecc85cD89210e1A19a8603544A917372/logs
